apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: azkexec
  name: azkexec
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: azkexec
    spec:
      containers:
      - env:
        - name: MYSQL_HOST
          value: mysql
        image: rinscy/azkaban-execserver:3.1.0
        name: azkexec
        ports:
        - containerPort: 12321
        resources: {}
      restartPolicy: Always
status: {}
