apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: azkweb
  name: azkweb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: azkweb
    spec:
      containers:
      - env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_ROOT_PASSWORD
          value: password
        image: rinscy/azkaban-webserver:3.1.0
        name: azkweb
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
status: {}
